name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_call:
    secrets:
        API:
          required: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Launch linter
        run: pnpm lint

  nest-test:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: echo "${{ secrets.API }}" > .env

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Run tests coverage
        run: pnpm test:cov

      - name: Run tests end to end
        run: pnpm test:e2e

  build:
    runs-on: ubuntu-latest
    needs: [nest-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: echo "${{ secrets.API }}" > .env

      - name: Build full compose
        run: docker-compose build
